postgresql:
  url: jdbc:postgresql://localhost:5432/starcode_database
  username: starcode
  password: starcode

logging:
  level:
    com.zaxxer.hikari: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#spring:
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
#      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration