server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  tomcat:
    threads:
      max: 40

spring:
  datasource:
    url: ${postgresql.url}
    username: ${postgresql.username}
    password: ${postgresql.password}
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      maximum-pool-size: 150
      minimum-idle: 20
      connection-timeout: 3000
      max-lifetime: 600000
      idle-timeout: 30000

    jpa:
      open-in-view: false
      show-sql: false
      hibernate:
        ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true
  threads:
    virtual:
      enabled: true

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  api-docs:
    version: OPENAPI_3_0